# Finacial Sector and its impact on Economy&Growth and Social Development

Finacial sector plays a cruial role on economy of a country and it also helps us to measure how much social development does a country has grown through that period. Direct investments from foreign countries increases the GDP which will help the nation to attain a stable economy. All the developed contries suchs as USA, England, Australia have a good finacial sector and that helped them have a steady economy and growth, we witnessed this in the pandemic itself. A country value depends upon its stock market and economy, understading how econmy helps the nation and its people is very important. By studying the economy and finacial sector one would gain knowledge how money is traded and this will help them personally to be successful in their personal life.

# What questions do you have in mind and would like to answer?

what various factors are responsible for an increment or decrement of a econmy and how finacial sector works, I would like to find answer for these questions.

Countries: Malaysia, Georgia, Russian Federation, China, Thailand

Time Period : 2000 - 2018

The below pie charts indicates the direct investement of foriegn countries to the respective countries and what percent of their GPD consits of this foreign direct investments.

In [18]:
import pandas as pd
import plotly
import plotly.express as px

In [19]:
Data_url = 'https://raw.githubusercontent.com/Sukesh-bitragunta/Sukesh_Data690/main/world_development_explorer/GDP.csv'

df = pd.read_csv(Data_url)

In [20]:
df.head()

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
0,0,2000,0.985384,BM.KLT.DINV.WD.GD.ZS,AUS,Australia,East Asia & Pacific,High income,Not classified
1,1,2001,3.529780,BM.KLT.DINV.WD.GD.ZS,AUS,Australia,East Asia & Pacific,High income,Not classified
2,2,2002,1.764128,BM.KLT.DINV.WD.GD.ZS,AUS,Australia,East Asia & Pacific,High income,Not classified
3,3,2003,3.979076,BM.KLT.DINV.WD.GD.ZS,AUS,Australia,East Asia & Pacific,High income,Not classified
4,4,2004,1.593224,BM.KLT.DINV.WD.GD.ZS,AUS,Australia,East Asia & Pacific,High income,Not classified

In [28]:
df_2000_GDP = df.query("Year == 2000").query("indicator == 'BM.KLT.DINV.WD.GD.ZS'")
df_2000_GDP

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
0,0,2000,0.985384,BM.KLT.DINV.WD.GD.ZS,AUS,Australia,East Asia & Pacific,High income,Not classified
21,21,2000,0.003747,BM.KLT.DINV.WD.GD.ZS,BGD,Bangladesh,South Asia,Lower middle income,IDA
42,42,2000,0.380733,BM.KLT.DINV.WD.GD.ZS,CHN,China,East Asia & Pacific,Upper middle income,IBRD
63,63,2000,0.111163,BM.KLT.DINV.WD.GD.ZS,GEO,Georgia,Europe & Central Asia,Upper middle income,IBRD
84,84,2000,0.108783,BM.KLT.DINV.WD.GD.ZS,IND,India,South Asia,Lower middle income,IBRD
105,105,2000,0.906285,BM.KLT.DINV.WD.GD.ZS,JPN,Japan,East Asia & Pacific,High income,Not classified
126,126,2000,2.160207,BM.KLT.DINV.WD.GD.ZS,MYS,Malaysia,East Asia & Pacific,Upper middle income,IBRD
147,147,2000,1.223991,BM.KLT.DINV.WD.GD.ZS,RUS,Russian Federation,Europe & Central Asia,Upper middle income,IBRD
168,168,2000,0.012247,BM.KLT.DINV.WD.GD.ZS,LKA,Sri Lanka,South Asia,Lower middle income,IBRD

# In 2000
Malaysia had more than 36 pecent of foriegn direct investements that directly contributes their GDP in year 2000

Russian Federation had around 20.8 percent and the difference between Australia and Japan is ver minimal that they are almost equal. China, Georgia, Thailand, India, Sri Lanka had less than 10 percent in 2000.

In [24]:
fig = px.pie(df_2000_GDP, values='value', names='Country Name', title='2000 total GDP per capita Comparision between given nations.',template=list(plotly.io.templates.keys())[5])
fig.update_traces(textposition='inside', textinfo='percent+label')
fig.update_layout(showlegend=True)

fig.show()

# In 2018

In [27]:
df_2018_GDP = df.query("Year == 2018").query("indicator == 'BM.KLT.DINV.WD.GD.ZS'")
df_2018_GDP

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
18,18,2018,0.019256,BM.KLT.DINV.WD.GD.ZS,AUS,Australia,East Asia & Pacific,High income,Not classified
39,39,2018,0.007010,BM.KLT.DINV.WD.GD.ZS,BGD,Bangladesh,South Asia,Lower middle income,IDA
60,60,2018,1.029352,BM.KLT.DINV.WD.GD.ZS,CHN,China,East Asia & Pacific,Upper middle income,IBRD
81,81,2018,1.668253,BM.KLT.DINV.WD.GD.ZS,GEO,Georgia,Europe & Central Asia,Upper middle income,IBRD
102,102,2018,0.422707,BM.KLT.DINV.WD.GD.ZS,IND,India,South Asia,Lower middle income,IBRD
123,123,2018,3.180896,BM.KLT.DINV.WD.GD.ZS,JPN,Japan,East Asia & Pacific,High income,Not classified
144,144,2018,1.606876,BM.KLT.DINV.WD.GD.ZS,MYS,Malaysia,East Asia & Pacific,Upper middle income,IBRD
165,165,2018,1.893220,BM.KLT.DINV.WD.GD.ZS,RUS,Russian Federation,Europe & Central Asia,Upper middle income,IBRD
186,186,2018,0.077142,BM.KLT.DINV.WD.GD.ZS,LKA,Sri Lanka,South Asia,Lower middle income,IBRD

By 2018 Thailand had nearly 25.7 percent of foriegn investements in their GDP, Japan Had almost 24 percent Russian Federation with 14.2 percent and Georgia 12.5 percent and Malaysia are almost equal. China, India, Sri Lanka and Australia had least foriegn investement.

This tell us that over the course of 2 decades Thaliand had progressed so much and china had lost its investors. This indicates that the Thailand had increment in their GDP and possibly in other aspects also. We can also conculde that the countries with less foriegn investements had most probably had a stble income which made them require very less foriegn investements

In [26]:
fig = px.pie(df_2018_GDP, values='value', names='Country Name', title='2018 total GDP per capita Comparision between given nations.',template=list(plotly.io.templates.keys())[5])
fig.update_traces(textposition='inside', textinfo='percent+label')
fig.update_layout(showlegend=True)

fig.show()

In [30]:
data = 'https://raw.githubusercontent.com/DATA-690-SPRING-2022/Sukesh_Data690/main/world_development_explorer/equity.csv'

df1 = pd.read_csv(data)

In [31]:
df1.head()

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
0,0,2000,-4.861363e+08,BX.PEF.TOTL.CD.WD,AUS,Australia,East Asia & Pacific,High income,Not classified
1,1,2001,7.388129e+09,BX.PEF.TOTL.CD.WD,AUS,Australia,East Asia & Pacific,High income,Not classified
2,2,2002,4.645470e+08,BX.PEF.TOTL.CD.WD,AUS,Australia,East Asia & Pacific,High income,Not classified
3,3,2003,1.244617e+10,BX.PEF.TOTL.CD.WD,AUS,Australia,East Asia & Pacific,High income,Not classified
4,4,2004,-2.458597e+10,BX.PEF.TOTL.CD.WD,AUS,Australia,East Asia & Pacific,High income,Not classified